spring.application.name: DiscordBot

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:C:/Users/Aaron/IdeaProjects/database
    driverClassName: org.h2.Driver
    username: root
    password: root
